/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IVPContractEventsInterface extends ethers.utils.Interface {
  functions: {};

  events: {
    "Delegate(address,address,uint256,uint256)": EventFragment;
    "Revoke(address,address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Delegate"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Revoke"): EventFragment;
}

export type DelegateEvent = TypedEvent<
  [string, string, BigNumber, BigNumber] & {
    from: string;
    to: string;
    priorVotePower: BigNumber;
    newVotePower: BigNumber;
  }
>;

export type RevokeEvent = TypedEvent<
  [string, string, BigNumber, BigNumber] & {
    delegator: string;
    delegatee: string;
    votePower: BigNumber;
    blockNumber: BigNumber;
  }
>;

export class IVPContractEvents extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IVPContractEventsInterface;

  functions: {};

  callStatic: {};

  filters: {
    "Delegate(address,address,uint256,uint256)"(
      from?: string | null,
      to?: string | null,
      priorVotePower?: null,
      newVotePower?: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber],
      {
        from: string;
        to: string;
        priorVotePower: BigNumber;
        newVotePower: BigNumber;
      }
    >;

    Delegate(
      from?: string | null,
      to?: string | null,
      priorVotePower?: null,
      newVotePower?: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber],
      {
        from: string;
        to: string;
        priorVotePower: BigNumber;
        newVotePower: BigNumber;
      }
    >;

    "Revoke(address,address,uint256,uint256)"(
      delegator?: string | null,
      delegatee?: string | null,
      votePower?: null,
      blockNumber?: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber],
      {
        delegator: string;
        delegatee: string;
        votePower: BigNumber;
        blockNumber: BigNumber;
      }
    >;

    Revoke(
      delegator?: string | null,
      delegatee?: string | null,
      votePower?: null,
      blockNumber?: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber],
      {
        delegator: string;
        delegatee: string;
        votePower: BigNumber;
        blockNumber: BigNumber;
      }
    >;
  };

  estimateGas: {};

  populateTransaction: {};
}
