/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IFtsoManager, IFtsoManagerInterface } from "../IFtsoManager";

const _abi = [
  {
    inputs: [],
    name: "getCurrentPriceEpochData",
    outputs: [
      {
        internalType: "uint256",
        name: "_priceEpochId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_priceEpochStartTimestamp",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_priceEpochEndTimestamp",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_priceEpochRevealEndTimestamp",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_currentTimestamp",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getCurrentRewardEpoch",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPriceEpochConfiguration",
    outputs: [
      {
        internalType: "uint256",
        name: "_firstPriceEpochStartTs",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_priceEpochDurationSeconds",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_revealEpochDurationSeconds",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_rewardEpoch",
        type: "uint256",
      },
    ],
    name: "getRewardEpochVotePowerBlock",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "rewardEpochDurationSeconds",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "rewardEpochs",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "votepowerBlock",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "startBlock",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "startTimestamp",
            type: "uint256",
          },
        ],
        internalType: "struct IFtsoManager.RewardEpochData",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IFtsoManager__factory {
  static readonly abi = _abi;
  static createInterface(): IFtsoManagerInterface {
    return new utils.Interface(_abi) as IFtsoManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFtsoManager {
    return new Contract(address, _abi, signerOrProvider) as IFtsoManager;
  }
}
