/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IIFtsoRewardManager,
  IIFtsoRewardManagerInterface,
} from "../IIFtsoRewardManager";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "authorizedAmountWei",
        type: "uint256",
      },
    ],
    name: "DailyAuthorizedInflationSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "amountReceivedWei",
        type: "uint256",
      },
    ],
    name: "InflationReceived",
    type: "event",
  },
  {
    inputs: [],
    name: "activate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "active",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address payable",
        name: "_recipient",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "_rewardEpochs",
        type: "uint256[]",
      },
    ],
    name: "claimReward",
    outputs: [
      {
        internalType: "uint256",
        name: "_rewardAmount",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address payable",
        name: "_recipient",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "_rewardEpochs",
        type: "uint256[]",
      },
      {
        internalType: "address[]",
        name: "_dataProviders",
        type: "address[]",
      },
    ],
    name: "claimRewardFromDataProviders",
    outputs: [
      {
        internalType: "uint256",
        name: "_rewardAmount",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_rewardEpochId",
        type: "uint256",
      },
    ],
    name: "closeExpiredRewardEpoch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "deactivate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "addresses",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "weights",
        type: "uint256[]",
      },
      {
        internalType: "uint256",
        name: "totalWeight",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "epochId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "ftso",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "priceEpochDurationSeconds",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "currentRewardEpoch",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "priceEpochEndTime",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "votePowerBlock",
        type: "uint256",
      },
    ],
    name: "distributeRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_rewardEpoch",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_dataProvider",
        type: "address",
      },
      {
        internalType: "address",
        name: "_claimer",
        type: "address",
      },
    ],
    name: "getClaimedReward",
    outputs: [
      {
        internalType: "bool",
        name: "_claimed",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_dataProvider",
        type: "address",
      },
    ],
    name: "getDataProviderCurrentFeePercentage",
    outputs: [
      {
        internalType: "uint256",
        name: "_feePercentageBIPS",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_dataProvider",
        type: "address",
      },
    ],
    name: "getDataProviderScheduledFeePercentageChanges",
    outputs: [
      {
        internalType: "uint256[]",
        name: "_feePercentageBIPS",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "_validFromEpoch",
        type: "uint256[]",
      },
      {
        internalType: "bool[]",
        name: "_fixed",
        type: "bool[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_rewardEpoch",
        type: "uint256",
      },
    ],
    name: "getEpochReward",
    outputs: [
      {
        internalType: "uint256",
        name: "_totalReward",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_claimedReward",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getEpochsWithClaimableRewards",
    outputs: [
      {
        internalType: "uint256",
        name: "_startEpochId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_endEpochId",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_beneficiary",
        type: "address",
      },
    ],
    name: "getEpochsWithUnclaimedRewards",
    outputs: [
      {
        internalType: "uint256[]",
        name: "_epochIds",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getRewardEpochToExpireNext",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_beneficiary",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_rewardEpoch",
        type: "uint256",
      },
    ],
    name: "getStateOfRewards",
    outputs: [
      {
        internalType: "address[]",
        name: "_dataProviders",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "_rewardAmounts",
        type: "uint256[]",
      },
      {
        internalType: "bool[]",
        name: "_claimed",
        type: "bool[]",
      },
      {
        internalType: "bool",
        name: "_claimable",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_beneficiary",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_rewardEpoch",
        type: "uint256",
      },
      {
        internalType: "address[]",
        name: "_dataProviders",
        type: "address[]",
      },
    ],
    name: "getStateOfRewardsFromDataProviders",
    outputs: [
      {
        internalType: "uint256[]",
        name: "_rewardAmounts",
        type: "uint256[]",
      },
      {
        internalType: "bool[]",
        name: "_claimed",
        type: "bool[]",
      },
      {
        internalType: "bool",
        name: "_claimable",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_rewardEpoch",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_dataProvider",
        type: "address",
      },
    ],
    name: "getUnclaimedReward",
    outputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_weight",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_feePercentageBIPS",
        type: "uint256",
      },
    ],
    name: "setDataProviderFeePercentage",
    outputs: [
      {
        internalType: "uint256",
        name: "_validFromEpoch",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IIFtsoRewardManager__factory {
  static readonly abi = _abi;
  static createInterface(): IIFtsoRewardManagerInterface {
    return new utils.Interface(_abi) as IIFtsoRewardManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IIFtsoRewardManager {
    return new Contract(address, _abi, signerOrProvider) as IIFtsoRewardManager;
  }
}
