/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IVPContractEvents,
  IVPContractEventsInterface,
} from "../IVPContractEvents";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "priorVotePower",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newVotePower",
        type: "uint256",
      },
    ],
    name: "Delegate",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "delegator",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "delegatee",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "votePower",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "blockNumber",
        type: "uint256",
      },
    ],
    name: "Revoke",
    type: "event",
  },
];

export class IVPContractEvents__factory {
  static readonly abi = _abi;
  static createInterface(): IVPContractEventsInterface {
    return new utils.Interface(_abi) as IVPContractEventsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVPContractEvents {
    return new Contract(address, _abi, signerOrProvider) as IVPContractEvents;
  }
}
